backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)media_folder: "public/uploads"   # Actual location in the repo

media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "assets/images" # The src attribute for uploaded media

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "src/pages/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
fields:
  - { label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/MarkdownPostLayout.astro" }
  - { label: "Title", name: "title", widget: "string" }
  - { label: "Publish Date", name: "pubDate", widget: "datetime" }
  - { label: "Description", name: "description", widget: "string" }
  - { label: "Author", name: "author", widget: "string" }
  - label: "Featured Image"
    name: "image"
    widget: "object"
    fields:
      - { label: "Image URL", name: "url", widget: "image" }
      - { label: "Alt Text", name: "alt", widget: "string" }
  - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
  - { label: "Body", name: "body", widget: "markdown" }

